export const FETCH_CATEGORY = 'FETCH_CATEGORY'
export const START_LOADING_CAT = 'START_LOADING_CAT'
export const END_LOADING_CAT = 'END_LOADING_CAT'

export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID'
export const LIKE_PRODUCT = 'LIKE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const START_LOADING_PROD = 'START_LOADING_PROD'
export const END_LOADING_PROD = 'END_LOADING_PROD'

export const CREATE_CART = 'CREATE_CART'
export const GET_CART_BY_USERID = 'GET_CART_BY_USERID'
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const EMPTY_CART = 'EMPTY_CART';
export const UPDATE_ORDER_ITEM_Q = 'UPDATE_ORDER_ITEM_Q';
export const START_LOADING_CART = 'START_LOADING_CART'
export const END_LOADING_CART = 'END_LOADING_CART'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_ERROR_RESET = `AUTH_ERROR_RESET`
export const AUTH_START_LOADING = `AUTH_START_LOADING`
export const AUTH_END_LOADING = `AUTH_END_LOADING`
export const AUTH = 'AUTH'

export const START_LOADING_DATA = 'START_LOADING_DATA'
export const END_LOADING_DATA = 'END_LOADING_DATA'
export const DATA_ERROR = 'DATA_ERROR'
export const DATA_ERROR_RESET = 'DATA_ERROR_RESET'

